version: '2'

services:
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=noveo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - back-tier

  fpm:
    image: dochupin/noveo_api:latest
    depends_on:
      - db
    networks:
      - back-tier
      - front-tier

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fpm
    networks:
      - front-tier

networks:
  back-tier:
  front-tier: